### ISSUE TITLE
No data connection

### ISSUE THREAD

**Issue by mgateno** [SuperCheese21/vatscan-react-native#20]
There is no connection to the VATSIM data. Map and list are empty. I believe their dataset changed

**Comment by Stracenzo** [comment]
Just downloaded the app and I have the same problem, no data with 0 Clients on the top left

**Comment by SuperCheese21** [comment]
Bug has been fixed! Update has been pushed to the Play Store

**Comment by Stracenzo** [comment]
Downloaded again from the playstore and now I get  unable to fetch ARTCC data error
